version: '3.4'

services:
  shopping-mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  catalog.api:
    image: api/catalog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://shopping-mongo:27017"
    depends_on:
      - shopping-mongo
    ports:
      - "8000:80"